# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: base_to_pc.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'base_to_pc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62\x61se_to_pc.proto\".\n\x0b\x43oordinates\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"V\n\x08SentData\x12\x1e\n\x06\x63oords\x18\x01 \x01(\x0b\x32\x0c.CoordinatesH\x00\x12\x12\n\x08obstacle\x18\x02 \x01(\x02H\x00\x12\x0e\n\x04tilt\x18\x03 \x01(\x02H\x00\x42\x06\n\x04\x64\x61ta*?\n\nReturnType\x12\r\n\tUNDEFINED\x10\x00\x12\n\n\x06\x43OORDS\x10\x01\x12\x0c\n\x08OBSTACLE\x10\x02\x12\x08\n\x04TILT\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'base_to_pc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RETURNTYPE']._serialized_start=156
  _globals['_RETURNTYPE']._serialized_end=219
  _globals['_COORDINATES']._serialized_start=20
  _globals['_COORDINATES']._serialized_end=66
  _globals['_SENTDATA']._serialized_start=68
  _globals['_SENTDATA']._serialized_end=154
# @@protoc_insertion_point(module_scope)
